DSD-DBS/capella-dockerimages

- README.md
- t4c/Dockerfile
The username default username is now modified accordingly to the environment variable $T4C_USERNAME.
This resolves #13.
> Modify t4c username

- Makefile
- README.md
This will add a Makefile that has goals to build all images.
Resolves #18.
> Add quick start instructions

- .gitignore
- capella/Dockerfile
- ease/debug/Dockerfile
- importer/Dockerfile
- importer/backup.sh
This PR contains two changes: 
1. Allow build of the ease debug image with restricted internet connections. In this case, users have to provide the packages manually. 
2. Read git email from environment variable during importer script.
> Offline build

- README.md
> docs: Add wiki reference and explanation to download section

- README.md
- remote/Dockerfile
- remote/autostart
the default value for the introduced env var
RESTART_CAPELLA is 1.
> feat: add flag to control restart of capella

- remote/metrics.py
The service was bysy-looping (`while True: ...`). This made the service take 100% CPU.
This PR fixes that by running the Prometheus service on the main thread.
> Fix: reduce CPU usage of metrics service

- base/Dockerfile
- capella/Dockerfile
This solved issues that have been experienced with German umlauts in file names for instance.
> Setup locale

- capella/Dockerfile
> Add build argument to the corresponding stage scope

- README.md
> Add X11-Server proposal to documentation

- tests/conftest.py
- tests/test_read_only.py
- tests/test_t4c_repository_injection.py
It's allowed to specify no T4C repository
> Remove false negative test case

- .gitignore
- Makefile
- capella/.dockerignore.template
- capella/.dockerignore.template.license
- t4c/.dockerignore.template
- t4c/.dockerignore.template.license
> Only load required Capella version archive into Docker build context

- Makefile
- capella/Dockerfile
- capella_loop.sh
There are several issues when trying to build our stuff with arm architectures. This PR tries to fix some of these.
> M1 support

- Makefile
- remote/Dockerfile
Add feature to specify the UID for the techuser in the Makefile.
> Specify UID for techuser

- readonly/load_models.py
> fix: Allow loading multiple models from one repo

- README.md
- ci-templates/README.md
- ci-templates/gitlab/README.md
- ci-templates/gitlab/exporter.yaml
This PR adds a Gitlab CI template for the `exporter`.
> Gitlab CI template for `exporter`

- ci-templates/gitlab/README.md
- ci-templates/gitlab/image-builder.yml
This adds a Gitlab CI template to build the images automatically.
> Gitlab CI Image builder

- ci-templates/gitlab/README.md
- ci-templates/gitlab/model-validation.yml
Adds a Gitlab CI template for model validation
> Model validation

- ci-templates/gitlab/model-validation.yml
Adds support for entrypoints with spaces.
> Fix model validator template, quote environment variable

- .github/workflows/deploy-docker-images.yml
- Makefile
- capella/Dockerfile
- capella/install_dropins.py
- capella/versions/5.0.0/dropins.yml
- capella/versions/5.2.0/dropins.yml
- capella/versions/6.0.0/dropins.yml
- capella/versions/6.1.0/dropins.yml
- capella_loop.sh
- docs/docs/capella/base.md
- docs/docs/capella/introduction.md
> Push images for different dropins sets

- docs/docs/index.md
- t4c/docker_entrypoint.sh
A small improvement and a typo fix.
> Boyscouting

- jupyter-notebook/Dockerfile
- jupyter-notebook/docker-entrypoint.sh
> fix: Create `/shared` directory in Dockerfile

- capella/setup_workspace.py
Set the default merge mode for Git to "Last head (unmerged)
The default merge strategy is set to "Working tree (pre-merged to 'Ours')" in the Linux bundle. This strategy has caused problems with the EMF Diff/Merge tool. In these cases, the Diff/Merge editor crashed with error messages like IndexOutOfBoundsException and "Cannot compare models". EMF Diff/Merge has shown to be much more stable when the option was set to "Last head (unmerged)"
The configuration is also available in the UI:
MacOS: Capella > Settings > Version Control (Team) > Git > Diff/Merge > Merge tool content
Linux: Window > Preferences > Version Control (Team) > Git > Merge tool content
Existing workspaces are modified and the option is replaced with the new strategy (if set to another strategy), new workspaces get the …
> feat: Set EGit merge strategy "Last head" as default

- docs/docs/index.md
Before:
- no consistency between colors in diagram and links
- missing links to eclipse and jupyter base
After:
> fix: Properly apply colors and add missings links

- Makefile
Pass the connection method to all Make targets which run remote images.
> build(dev): Add xpra support for all "remote" Make targets

- .github/workflows/deploy-docker-images.yml
- Makefile
- capella/install_dropins.py
- capella/versions/5.0.0/dropins.yml
- capella/versions/5.2.0/dropins.yml
- capella/versions/6.0.0/dropins.yml
- capella/versions/6.1.0/dropins.yml
- docs/docs/capella/base.md
- docs/docs/capella/provisioning.md
The `ModelsImporter` dropin is used for automatic session provisioning.
> feat: Load `ModelsImporter` dropin automatically

- .hadolint.yaml
- Makefile
- base/Dockerfile
- capella/Dockerfile
- pure-variants/setup_workspace_purevariants.py
- t4c/Dockerfile
Inject known servers into pure::variants containers.
> feat: Inject known pure::variants servers

- remote/supervisord.xpra.conf
Resolves https://github.com/DSD-DBS/capella-dockerimages/issues/284.
Resolves https://github.com/DSD-DBS/capella-dockerimages/issues/278.
> feat: Resolve flickering of Eclipse with Xpra connection method

- capella/install_dropins.py
An installable unit (IU) is meant here.
> fix: Correct arg name suffix

- t4c/docker_entrypoint.sh
> fix(t4c): Use correct venv for backup & exporter

- .pre-commit-config.yaml
- capella/versions/5.0.0/dropins.yml
- capella/versions/5.2.0/dropins.yml
Requires `yq` to be installed locally.
> ci: Sort keys in `dropins.yml` files automatically

- remote/error.html
When Xpra is not ready yet (Bad Gateway), add an auto-refresh so that users are connected automatically.
> feat: Add auto-refresh for Xpra startup page

- remote/rc.xml
> fix: Only fullscreen the main window in Openbox

- capella/autostart
- docs/docs/remote.md
- remote/Dockerfile
- remote/bg-saved.cfg
It hasn't been working for a while anyways.
> chore: Remove nitrogen from remote docker image

- remote/Dockerfile
- remote/client-inject.js
Closes #351
Somewhat improves #350
> fix: Increase OPEN_TIMEOUT and move injects to own file

- remote/metrics.py
Add several metrics from Xpra (using the xpra info command behind the scenes). This can be useful for troubleshooting any potential session issues.
> feat: Add prometheus metrics tracking Xpra performance

- remote/metrics.py
> fix: Skip metrics on permission denied

- base/Dockerfile
- jupyter-notebook/Dockerfile
- jupyter-notebook/docker-entrypoint.sh
Certifi doesn't trust the system certificate store by default.
Resolves #370.
> feat: Load certificates into certifi certificate store

- base/Dockerfile
- capella/autostart
- docs/docs/git-hooks/git-hooks.md
- eclipse/autostart
- jupyter-notebook/Dockerfile
- jupyter-notebook/supervisord.conf
- papyrus/autostart
- remote/startup.sh
- remote/supervisord.conf
- remote/supervisord.xpra.conf
- remote/supervisord.xrdp.conf
A central log location makes the log collection easier.
> feat: Bundle all session related logs in `/var/log/session`

- capella/Dockerfile
Unfortunately it looks like it's not possible to hide the other locations.
Closes #262
> feat: Add /workspace to file explorer sidebar

- .hadolint.yaml
- builder/Dockerfile
- capella/Dockerfile
- eclipse/Dockerfile
- local-git-server/Dockerfile
- papyrus/Dockerfile
- pure-variants/Dockerfile
- remote/Dockerfile
- t4c/Dockerfile
Since there's a bunch of changes, we should make sure to thoroughly test all images before merging
> fix: Enable stronger Hadolint linting and fix issues

- .gitignore
- .pre-commit-config.yaml
- capella/Dockerfile
- capella/install_dropins.py
- capella/patch.sh
- ci-templates/gitlab/image-builder.yml
- cli/cdi/args.py
- cli/cdi/capella/build.py
- cli/cdi/capella/run.py
- cli/cdi/docker.py
- cli/cdi/eclipse/run.py
- cli/cdi/jupyter/run.py
- cli/cdi/papyrus/run.py
- cli/cdi/syncer/run.py
- docs/docs/capella/base.md
Users can define a `dropins.overwrites.yml` to define their own dropins. This can also be used to install patches and can be used as more intuitive approach than the `patch_info.csv`
> feat: Add option to deviate from default dropins

- t4c/t4c_cli/backup.py
> fix(backup): Handle dates of older Capella versions in commit history
