- readonly/Dockerfile
- readonly/git_askpass.py
- readonly/prepare_workspace.py
- readonly/startup.sh
This adds support for readonly Dockerimages / -containers. 
Readonly containers will pull the model from a git repository, loads the model into the workspace via EASE and spawns up a RDP session.
> Readonly, resolves DSD-DBS/capella-collab-manager#7

- capella/Dockerfile
- remote/startup.sh
This fixes a indeterministic behaviour.
tee did trucate the file sometimes before it was substituted, which resulted in an empty file.
Resolves #14
> Fix license injection

- README.md
- readonly/startup.sh
The Environment variables `GIT_REVISION` and  `GIT_DEPTH` are used such that git models can be cloned in different ways:
1. If `GIT_REVISION ` is an empty string and `GIT_DEPTH` is equal to '0': the complete repository is cloned.
2. If `GIT_REVISION ` is an empty string and `GIT_DEPTH` is equal to '1': only the latest commits of all branches near the tips are cloned.
3.  If `GIT_REVISION ` is not an empty string and `GIT_DEPTH` is equal to '0': the chosen branch - `GIT_REVISION` - with its complete history is cloned.
4. If `GIT_REVISION ` is not an empty string and `GIT_DEPTH` is equal to '1': only the latest commits of the chosen branch - `GIT_REVISION` - is cloned.
5.  Otherwise the procedure failed.
Resolves #7.
> Accelerate cloning of git models

- base/Dockerfile
Zip is used by the download feature of capella-collab-manager (https://github.com/DSD-DBS/capella-collab-manager/pull/201) to package files before download. Unfortunately tar was not sufficient: that file format is not understood by Windows.
> Add zip to the base image

- ease/Dockerfile
This PR fixes an error in the `capella/ease/remote` image which prevented Capella to start. Permissions for the installed EASE extensions were set to root.
> fix: use techuser for ease installation

- .github/workflows/deploy-docker-images.yml
- Makefile
- pytest.ini
- tests/test_read_only.py
- tests/test_repositories_seeding.py
Simplify build script and test builds.
* Builds and uploads Capella 5.0, 5.1 and 6.0 (See "packages")
* Builds adds a label with the git hash, so we can always trace a container to the commit
* Runs tests as part of the build
* Builds on every push
Resolves #53
> Build images in CI

- .github/workflows/deploy-docker-images.yml
- Makefile
- tests/test_read_only.py
- tests/test_repositories_seeding.py
Use `DOCKER_PREFIX` and `DOCKER_TAG` environment variables for tests. It allows adding tests without changing the GH actions in the future. 
And it shortens the names of the actions a bit, they were not readable in the commit view: 
New: 
Fixes #61.
> Use DOCKER_PREFIX and DOCKER_TAG environment for tests

- capella/setup_workspace.py
- readonly/load_models.py
- tests/test_read_only.py
When starting a read-only session, the entrypoint was not resolved properly. As we explicitly allow entrypoints with `/` (relative to the root of the Git repository), we should have support for it. 
In addition, I added the behavior to the tests.
Resolved #65.
> Add support for entrypoints starting with /

- .github/workflows/deploy-docker-images.yml
- Makefile
- capella_loop.sh
When you'd like to run tests or build images, please specify the
environment variable CAPELLA_VERSIONS as as comma-separated list of
semantic Capella versions, e.g., "5.0.0 5.2.0 6.0.0"
The environment variable CAPELLA_VERSION is not used anymore for
building or testing images. It is only used to run containers.
As there was no nice way to do it with GNU make, I've defined our own shell.
The result is nice. You can now run `make test` and test against all supported Capella versions.
> Multiple capella versions

- .gitignore
- Makefile
- README.md
- builder/Dockerfile
- builder/build_capella_from_source.sh
- builder/inject_architecture_into_pom.py
Adds a script + Docker image + README section to build Capella from source (including `aarch64` support).
> Build capella from source

- .gitignore
- Makefile
- capella/Dockerfile
This is a breaking change. CI templates have to be updated individually. 
With this PR, users can store archives for different build architectures on their disks and use them via the `BUILD_ARCHITECTURE` variable.
> Build architecture abstraction

- .github/CODEOWNERS
- ci-templates/gitlab/README.md
- ci-templates/gitlab/exporter.yml
- ci-templates/gitlab/model-validation.yml
Otherwise, environment variables are used as default when they are not defined. The script doesn't fail. This is unintended behaviour.
> Comment out default values for environment variables

- t4c/patch_t4c.sh
Fix for functionality added in #118 needed since the `installIU` list is not allowed to have whitespaces in it.
> Do not add whitespace after the comma

- base/Dockerfile
Git is commonly used in CI/CD environments.
> Add `git-lfs` to base image

- .gitlab-ci.yml
- .gitlab-ci.yml.license
- ci-templates/gitlab/image-builder.yml
- ci-templates/gitlab/release-train.yml
- docs/docs/ci-templates/gitlab/release-train.md
Adds the release train Gitlab CI template. With the release train, users can build images for new Capella versions on a specific trigger (e.g. manual trigger, on new releases or new Capella archives).
> Add release train Gitlab CI template

- ci-templates/gitlab/image-builder.yml
- docs/docs/ci-templates/gitlab/image-builder.md
- tests/conftest.py
This PR introduces two major enhancements to our CI/CD pipeline:
**Restricted Push to Production**: With this PR, we have implemented a restriction that allows images to be pushed to the production environment only when it is associated with a tag.
**Dynamic Docker Variable Resolution**: We have introduced a mechanism to dynamically resolve Docker variables based on the $ENVIRONMENT CI/CD variable. Previously, Docker variables were statically set which posed limitations on scalability and flexibility. Now, with this dynamic approach, it is much easier to add or modify environments as needed. This is accomplished by transforming the $ENVIRONMENT value to uppercase and using it to construct Docker registry related environment variables including DOCKER_REGISTRY, DOCKER_REGISTRY_USER, and …
> Add support for multiple environments

- .gitignore
- .gitlab-ci.yml
- Makefile
- capella/Dockerfile
- ci-templates/gitlab/image-builder.yml
- ci-templates/gitlab/release-train.yml
- docs/docs/eclipse/base.md
- docs/docs/index.md
- docs/docs/papyrus/base.md
- docs/docs/pure-variants.md
- docs/mkdocs.yml
- eclipse/Dockerfile
- eclipse/autostart
- papyrus/Dockerfile
- pure-variants/Dockerfile
To use `pure::variants` without Capella, this PR adds a `pure::variants` image which is based on Eclipse instead of Capella.
The `eclipse/base` image has been added and the image builder Gitlab CI template is updated.
Resolves #96
> Adds `pure::variants` images (based on Eclipse)

- .gitignore
- capella/Dockerfile
- capella/patch.sh
- ci-templates/gitlab/image-builder.yml
- t4c/Dockerfile
This PR enables the addition of feature patches not only to our T4C image but also to the Capella base image. We have transformed the `patch_t4c_sh` it into a more general `patch.sh` script, which is now integrated into the Capella base image. To apply feature patches to images built on the Capella base, it's necessary to ensure the availability of a directory containing the feature patches zip files and `patch_info.csv`. This directory then has to be provided in PATCH_DIR and then we only have to run patch.sh
> Extend capella base by feature patches

- docs/docs/capella/introduction.md
When dropins were added to the docker images the docs fore the `main` docker images tag were not updated.
This PR updates the documentation for that tag as well.
> docs: Update schema for main tag

- base/Dockerfile
- builder/Dockerfile
- capella/Dockerfile
- ci-templates/gitlab/diagram-cache.yml
- ci-templates/gitlab/image-builder.yml
- docs/docs/base.md
- ease/Dockerfile
- jupyter-notebook/Dockerfile
- jupyter-notebook/docker-entrypoint.sh
- readonly/Dockerfile
- remote/Dockerfile
- tests/local-git-server/Dockerfile
New `pip` versions do not like to install in "system" folders. However, this always worked for us, so we can keep doing it IMHO. Pip also does not like a `pip install --user` on Book worm.
The alternative is to set up venvs, but I think that's not needed for a (contained) docker image.
> Upgrade to Debian Bookworm

- Makefile
- ease/Dockerfile
- pyproject.toml
- readonly/load_models.py
- readonly/startup.sh
Resolves https://github.com/DSD-DBS/capella-dockerimages/issues/173
This json...
```json
[
{
"url": "https://github.com/DSD-DBS/coffee-machine",
"revision": "main",
"depth": 0,
"entrypoint": "coffee-machine-demo.aird"
},
{
"url": "https://github.com/DSD-DBS/coffee-machine",
"revision": "main",
"depth": 0,
"entrypoint": "coffee-machine-demo.aird"
},
{
"url": "https://github.com/DSD-DBS/coffee-machine",
"revision": "diagram-cache-workflow",
"depth": 0,
"entrypoint": "coffee-machine-demo.aird"
}
]
```
... produces this output: 
In general: 
- If there we have duplicates, add the sanitised revision to the project name.
- If there are still duplicates, count the projects and add a number as suffix.
- If we have even more duplicates, they are ignored.
> fix: Load multiple models with the same project name

- Makefile
- capella/Dockerfile
- eclipse/Dockerfile
- papyrus/Dockerfile
We were using the default memory limit from the default eclipse.ini files. In large projects, the memory limit can be reached quickly.
Therefore, we're increasing it to 5500m per default and give the user an option to configure it via the `MEMORY_LIMIT` build argument.
> perf: Increase memory limit to 5.5GB for Eclipse based tools

- jupyter-notebook/Dockerfile
- jupyter-notebook/jupyter_lab_config.py
Required for https://github.com/DSD-DBS/capella-collab-manager/pull/849
Notable changes: 
- `@jupyterlab/apputils-extension:announcements` is disabled now (no annoying dialogs anymore)
- A Jupyter configuration was added, but all configuration options are commented out (instead of one option). They can be added in the future, if wanted. The `Content-Security-Policy` is set if a `HOST` environment variable is provided to allow the embedding into iframes.
> feat: Allow embedding of Jupyter notebooks

- Makefile
- base/Dockerfile
- jupyter-notebook/Dockerfile
- jupyter-notebook/docker-entrypoint.sh
- jupyter-notebook/requirements_template.txt
- Added a `run-jupyter-notebook` target to the Makefile
- Install dependencies from requirements_template per default
- Update depdendencies automatically during container startup
- Use a global venv instead of `--break-system-packages`
- Change ownership of pip packages from root to techuser
Resolves #178
> feat(jupyter): Use global venv and update requirements from template

- ci-templates/github/diagram-cache/action.yml
- docs/docs/ci-templates/github/diagram-cache.md
- docs/docs/ci-templates/index.md
- docs/mkdocs.yml
See first working usage here: https://github.com/DSD-DBS/coffee-machine/pull/8
> feat: Add reusable Github action for the `diagram cache`

- jupyter-notebook/Dockerfile
- jupyter-notebook/requirements_template.txt
This PR adds support for [capellambse-context-diagrams](https://github.com/DSD-DBS/capellambse-context-diagrams) in the Jupyter Docker image. 
While I tested the functionality, I found a bug: JupyterLab printed a malformed JSON instead of proper HTML, PNG or SVG. Thanks to the great py-capellambse team, they already have a fix for it available: https://github.com/DSD-DBS/py-capellambse/pull/316 
The fix should be merged before we make the context diagrams available / this PR can be merged.
> feat(jupyter): Add support for capellambse-context-diagrams

- jupyter-notebook/jupyter_lab_config.py
The `HOST` environment variable is often used to determine the current host, not the origin host.
Therefore, we're changing the variable to `CSP_ORIGIN_HOST`.
This is a breaking change, but we're not aware of any usage yet.
> refactor!: Rename `HOST` to `CSP_ORIGIN_HOST`

- jupyter-notebook/Dockerfile
The Jupyter Collaboration extensions allows real-time collaboration across multiple sessions.
To start a shared session, click the "Share" button on the top right of the session and include the token in the link.
https://github.com/DSD-DBS/capella-dockerimages/assets/23395732/cd617216-362a-486e-9068-18f9077c91e2
Be careful: All users with the link can now access the whole session until session termination!
Related to https://github.com/DSD-DBS/capella-collab-manager/issues/678
> feat: Add jupyter-collaboration as extension

- jupyter-notebook/docker-entrypoint.sh
SIGTERM was not passed to the Jupyter process.
The Jupyter container has completely ignored the SIGTERM signal and could only be stopped by sending a SIGKILL signal.
With Docker, the container is killed after a grace period of 10 seconds per default. Kubernetes has a default grace period of 30 seconds.
> fix(jupyter): Handle SIGTERM properly

- capella/Dockerfile
- ease/Dockerfile
`capella/base` is also used to run Capella with `xvfb-run`. Therefore, we have to install xauth in the Capella base image.
The installation in the ease image is no longer necessary. It inherits the installation from the capella/base image.
> fix: Move xauth and dbus-x11 installation to capella/base

- jupyter-notebook/docker-entrypoint.sh
This feature is required for https://github.com/DSD-DBS/capella-collab-manager/pull/918. Shared volumes can be mounted to `/shared/<name>`, and a symlink is created from the notebooks workspace.
> feat: Add symlink from notebook workspace to `/shared`

- base/Dockerfile
- capella/Dockerfile
- ci-templates/gitlab/diagram-cache.yml
- ease/Dockerfile
- readonly/Dockerfile
- remote/Dockerfile
As a temporary solution, `--break-system-packages` was appended to all `pip install` commands in an earlier version.
This commit changes the behaviour to use a global venv. `--break-system-packages` is no longer needed on `pip install` commands.
> build: Add global venv for Python

- jupyter-notebook/docker-entrypoint.sh
This ensures that any error during the startup of jupyter will result in the error message.
> feat: Print failure message when error occurs

- base/Dockerfile
The installation of Neovim introduces also a `vim` command launching Neovim.
> feat: install `neovim` in base image

- readonly/startup.sh
- remote/Dockerfile
- remote/startup.sh
- tests/conftest.py
- tests/local-git-server/Dockerfile
The use of `passwd` is not possible in restricted environments. It produces `Authentication token manipulation error`.
In one of our environments, session creation stopped after an OpenShift cluster update to version 4.11.
Our suspect is the change of the Pod security admission. More information can be found in the release notes: https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html#ocp-4-11-auth-pod-security-admission
> feat: Change password by directly writing to `/etc/shadow`

- t4c/Dockerfile
In the default configuration, `xmi:id`s are not stable. This leads to a huge diff in Git in each commit.
With the added flags, the CDO IDs are used as xmi:id.
> fix: Add TeamForCapella flags for stable `xmi:id`s

- Makefile
This commit adds a new target to the Makefile,
which runs the TeamForCapella backup, but doesn't push it to a Git repository.
> build: Add new backup target for local environment

- ci-templates/gitlab/model-validation.yml
We run containers with techuser (non-root) but the environment is owned by root. This causes any git command to fail. This commit fixes the problem by adding `safe.directory` to the global git config.
> fix: Fix model validation

- t4c/backup.py
Checkout only the latest commit for a branch, just enough to create a new commit upon.
Fixes #209.
> feat: use shallow clones for backups

- base/hooks/+pre-commit-and-lfs.sh
The `+pre-commit-and-lfs.sh` file `exec`-d into pre-commit, and therefore never reached git-lfs. This PR removes exec to fix this.
> Improvements to global git hooks

- Makefile
- base/Dockerfile
- ci-templates/gitlab/image-builder.yml
- docs/Makefile
- docs/docs/capella/base.md
- docs/docs/remote.md
- docs/mkdocs.yml
- docs/requirements.txt
- remote/Dockerfile
- remote/nginx.conf
- remote/startup.sh
- remote/supervisord.conf
- remote/supervisord.xpra.conf
- remote/supervisord.xrdp.conf
[xpra](https://github.com/Xpra-org/xpra/) allows to run X11 programs in the Docker container and expose them to the local host.
We make use of [xpra-html5] client, which allows us to access the application in the browser - without any external software like Guacamole on the way.
xpra runs as non-root out of the box. Basic authentication is handled via nginx.
> feat: Support xpra as additional connection method for remote containers

- t4c/backup.py
This PR adds `-overrideExistingProject` to the backup call which ensures that copying of a project to the output folder does not fail. This ensures that also project having a space in there name are copied correctly.
> fix: Add `overrideExistingProject` to backup call

- Makefile
- capella/autostart
- capella/setup_workspace.py
- docs/docs/base.md
- docs/docs/jupyter/index.md
- eclipse/autostart
- jupyter-notebook/Dockerfile
- jupyter-notebook/docker-entrypoint.sh
- papyrus/autostart
- readonly/load_models.py
- readonly/startup.sh
- remote/autostart
- t4c/setup_workspace.py
In order to support one shared persistent workspace for multiple simultanious (capella) sessions, we need to make sure every session is starting in its own workspace.
To make it consistent, Jupyters `NOTEBOOKS_DIR` has been renamed to `WORKSPACE_DIR`.
See https://github.com/DSD-DBS/capella-collab-manager/issues/1004.
This is a breaking change: The environment variable `NOTEBOOKS_DIR` was replaced with  `WORKSPACE_DIR`.
> feat!: Configurable workspace directory

- base/hooks/+pre-commit-and-lfs.sh
- t4c/backup.py
Previously, the `-archiveProject` flag was set to false. As a result, the project imported from the T4C repository was made available as a simple directory, but all files of the project were flattened. This resulted in a `java.nio.file.File.FileAlreadyExistsException` exception when two images with the same name existed in different locations. This PR changes the `-archiveProject` flag to true, which ensures that the projects are passed as *.zip* files and their original structure is not changed. The archive is then simply unpacked, and as the original structure is retained using `-archiveProject true`, the previous unmessing step (i.e., moving images into a *images* and fragments into a *fragments* directory) is no longer necessary.
Resolves #151
> fix: Set `-archiveProject true`to avoid flatten

- t4c/backup.py
T4C uses an intersting encoding for project names described in more detail [here](https://en.wikipedia.org/wiki/Internationalized_Resource_Identifier). Since our projects shouldn't use any special characters anyways, we can avoid reproducing their encoding by simply adding characters to the safe list if encountering a project with such a character.
Resolves #142
> fix: Don't encode `@` in project name

- t4c/backup.py
This PR fixes a problem where reserved pattern symbols like `*` or `[...]` in a project name lead to a problem finding the corresponding archive. More specifically, the pattern for a project named `X_[YZ]_W` previously incorrectly matched `X_Y_W` or `X_Z_W` instead of `X_[YZ]_W`. This is now fixed by correctly escaping the project name.
> fix: Escape project name in pattern

- ci-templates/gitlab/diagram-cache.yml
This PR changes the diagram cache template so that it directly uses the py-capellambse CLI to execute it. This makes it more robust, as a change in py-capellambse does not affect the ci template. Additionally, a separate `$RESOURCES` was previously required, which is now directly included in `$ENTRYPOINT` being consistent with what the py-capellambse diagram cache expects.
> feat: Switch to CLI for diagram cache update

- .github/workflows/commits.yml
Global installations don't work since the release of version v19.0.0: https://github.com/conventional-changelog/commitlint/issues/3936
> ci: Install commitlint locally, not globally

- Makefile
- readonly/Dockerfile
- readonly/prepare_workspace.sh
- remote/startup.sh
After xpra support was introduced, the `supervisord` configuration was split into general, xrdp and xpra. Unfortunately, I forgot to load the new configuration files into the read-only images. As a result, neither xrdp nor xpra were started.
Another good side effect of this fix is that xpra is now supported for read-only sessions. I was also able to eliminate some code duplication by reusing the startup script from the remote container.
> fix: Start xrdp automatically for read-only sessions

- t4c/backup.py
- tests/test_backups.py
If the importer fails, a backup on the server was triggered. This can lead to an unresponsive server. Therefore, we disable the backups.
Currently, the following test fails. I have to investigate if it's related to this PR:
```
FAILED test_backups.py::test_model_backup_unhappy[t4c_server_container1-t4c_server_env1-t4c_backup_local_env1] - Failed: DID NOT RAISE <class 'RuntimeError'>
```
I've removed the test. Reason is available here: https://github.com/DSD-DBS/capella-dockerimages/issues/253
> fix: Disable backups after failed importer attempts

- Makefile
- docs/docs/remote.md
- remote/nginx.conf
- remote/startup.sh
With this commit, it's possible to pass the `XPRA_SUBPATH` variable to define a path that xpra will listen on.
> feat: Add support to serve xpra on subpath

- docs/docs/capella/base.md
- docs/docs/remote.md
- remote/nginx.conf
- remote/startup.sh
Instead of the basic authentication, we switch the authentication method to cookie based authentication. This makes the embedding in iframes easier.
In addition, the Content-Security-Policy origin host can be defined via the environment variable `XPRA_CSP_ORIGIN_HOST`.
> feat: Allow embedding in iframes with cookie-based authentication

- Makefile
- ci-templates/gitlab/exporter.yml
- docs/docs/capella/t4c/exporter.md
- docs/docs/capella/t4c/importer.md
- docs/docs/ci-templates/gitlab/t4c-export.md
- t4c/backup.py
- t4c/export.py
- tests/conftest.py
- tests/test_backups.py
- tests/test_exporter_git.py
- tests/test_exporter_local.py
This PR removes any code and related documentation that used the `HTTP` variables. This is possible because no T4C administrator operation should be performed in both the backup and export scripts, so we do not need to provide these variables. The fact that this is possible was discovered in https://github.com/DSD-DBS/capella-dockerimages/pull/249 and described in https://github.com/DSD-DBS/capella-dockerimages/issues/253.
I have successfully run all tests for version 5.2.0, 6.0.0 and 6.1.0 locally.
Resolves #253
> feat: Remove `HTTP` related code

- remote/Dockerfile
- remote/error.html
- remote/nginx.conf
When xpra is starting, it can lead to occasional 502 and 404 errors. This is nothing to worry about, but hard to understand for users. Therefore, we make the error a bit clearer.
> feat: Add custom error message during Xpra startup

- remote/Dockerfile
- remote/error.html
- remote/nginx.conf
Version 11 doesn't respect the URI parameters and the floating window is not disabled.
Version 12 doesn't connect to the session. Since it's still in beta, we should use it anyway.
> fix: Set `xpra-html5` version to `v10.1`

- builder/Dockerfile
The tag `3.11.1-bookworm` no longer exists.
Instead, use `3.11-bookworm`.
> fix(builder): Update removed Python Docker tag

- docs/mkdocs.yml
Loading fonts from Google Fonts is not GDPR compliant. The documentation will now use the system-font.
> docs: Disable font-loading from Google Fonts

- Makefile
Support loading of different workspaces from `volumes/workspaces` subdirectories instead of always using `volumes/workspace` as workspace.
> feat(dev): Make workspace configurable

- docs/docs/remote.md
- remote/nginx.conf
- remote/startup.sh
This commit removed the authentication layer for xpra based sessions. After this update, all xpra sessions will be exposed without authentication!
Reason for this change is a feature in the Capella Collaboration Manager, which automatically authenticates users against sessions (pre-authentication): https://github.com/DSD-DBS/capella-collab-manager/releases/tag/v3.1.0
If you don't use the Capella Collaboration Manager, you have to implement your own authentication mechanism.
BREAKING CHANGE: Authentication for xpra containers was removed.
> perf!: Remove authentication layer for xpra sessions

- t4c/t4c_cli/backup.py
- t4c/t4c_cli/export.py
- t4c/t4c_cli/util/config.py
This removes the direct use of `T4C_USERNAME` and `T4C_PASSWORD` within the T4C CLI and instead writes them to a file and then uses that file. This has the advantage that the credentials are no longer displayed directly within the command, reducing the risk of potential exposure, and is also the recommended way to provide the credentials described by OBEO.
All tests for versions 5.2.0, 6.0.0 and 6.1.0 were successful.
Resolves #270
> feat(t4c): Provide credentials via a file

- Makefile
- base/Dockerfile
- docs/docs/pure-variants.md
- pure-variants/Dockerfile
- pure-variants/setup_workspace_purevariants.py
- The workspace can be configured with the `WORKSPACE_DIR` environment variable.
- In addition, a new variable `DOCKER_DEBUG_FLAGS` was added to group the list of debug flags.
- For better layer caching, the `/opt/setup/setup_workspace_purevariants.py` was moved to another layer.
- A new `debug-eclipse/remote/pure-variants` was added.
- Instructions for pure::variants dependency download were removed (they are no longer supported). 
- X11 forwarding is now enabled per default when using the debug mode.
> feat: Make pure::variants workspace configurable

- jupyter-notebook/Dockerfile
The latest node version in debian:bookworm is v18.19.0. Multiple vulnaribilities haven been reported for this version.
Even though we don't expose node, it's better to have them fixed.
> build: Bump node version in Jupyter image

- Makefile
- docs/docs/jupyter/index.md
- jupyter-notebook/Dockerfile
- jupyter-notebook/docker-entrypoint.sh
Specify a environment variable `JUPYTER_ADDITIONAL_DEPENDENCIES` with a comma-separated list of pip dependencies (trusted values only!).
Additionally, weasyprint is installed per default. We believe that it's useful to generate model derived PDFs.
Resolves https://github.com/DSD-DBS/capella-dockerimages/issues/250
> feat: Allow additional dependencies during runtime

- Makefile
- docs/docs/jupyter/index.md
- jupyter-notebook/Dockerfile
- jupyter-notebook/docker-entrypoint.sh
- jupyter-notebook/jupyter_metrics.py
- jupyter-notebook/supervisord.conf
Add a new endpoint on port 9118, which exposes the idletime of the JupyterLab container.
> feat: Expose idletime of Jupyter container via metrics endpoint

- ci-templates/gitlab/image-builder.yml
It doesn't seem to be compatible as of now.
> fix: Disable pure::variants build for Capella 7.0.0

- t4c/t4c_cli/backup.py
- t4c/t4c_cli/export.py
The '1 projects imports succeeded' message was changed to '1 project import succeeded' in TeamForCapella 7.0.0
> fix: Consider changed success message for importer / exporter

- base/Dockerfile
- jupyter-notebook/Dockerfile
- t4c/Dockerfile
Get rid of pynvim, which is flagged as malicious in XRAY.
Resolves #313.
> fix: Don't install recommended packages in base image

- Makefile
- docs/docs/capella/base.md
Automatic installation of dropins can fail for various reasons, mostly internet connectivity. Also, it slows down the build process and dropins are often not needed.
In addition, this commit adds documentation about the manual installation of dropins again.
> build: Disable automatic installation of dropins by default

- base/Dockerfile
At least one user uses `ssh-agent` forwarding to access ssh keys in the container. An SSH client might be helful for other use-cases like cloning via SSH in general.
I raised the topic in the team and there were no bojections to add the 20MB large installation of `openssh-client` to the image.
> feat: Install `ssh` client in base image

- .github/workflows/deploy-docker-images.yml
- .pre-commit-config.yaml
- capella/download_archive.py
- pyproject.toml
Update pre-commit hooks to the latest versions and limit the pre-commit version to <4.0.0 because of
<https://github.com/PyCQA/docformatter/issues/289>.
> ci: Update pre-commit hooks

- .github/workflows/deploy-docker-images.yml
- Makefile
- capella/Dockerfile
- capella/download_archive.py
- docs/docs/capella/base.md
Background:
The server endpoint behind the Capella download URL that has been used so far seems to blacklist GitHub actions IP addresses. This commit allows setting the Capella download URL via an environment variable to use a different mirror to download Capella.
> ci: Allow setting the Capella download URL

- capella/setup/setup_workspace.py
This makes clear, that these funcs are never called from somewhere outside of the present module.
> refactor: Make non-API funcs private

- .github/workflows/deploy-docker-images.yml
- .pre-commit-config.yaml
docformatter is not compatible yet in the latest release, therefore pointing to the latest commit hash on the main branch.
> ci: Bump `pre-commit` to latest version

- Makefile
- capella/setup/disable_semantic_browser_auto_refresh.py
- docs/docs/capella/base.md
When the semantic browser is in the foreground and the displayed setting is active in its toolbar, the UI can freeze for bigger models and every change of model element selection.
It takes its time to load the context of related elements and this bootle neck makes bigger models nearly unusable espoecially for models on a remote Team4Capella (T4C) server.
This is why it has been decided to introduce an according configuration option that disables this toolbar option for every new Capella session.
The default of Capella for a freshly created workspace makes this auto-refresh active as illustrated.
This PR adds a new environment variable which allows to deviate from the default and disables the auto-refresh of the semantic browser, when the environment variables is set to …
> feat: Disable the auto-refresh of the semantic browser on Capella session startup

- remote/Dockerfile
We were running on a relatively old version of xpra html5.
> feat: Bump `xpra-html5` to latest version

- capella/setup/setup_workspace.py
Change Capella settings to force help to be shown using the internal browser. There was discussion about exposing help as outside the container as well, but this is probably not worth the effort.
Closes #301
Closes #159
Closes DSD-DBS/capella-collab-manager#753
Closes DSD-DBS/capella-collab-manager#576
> fix: Use internal browser for help instead of broken external one

- remote/Dockerfile
By default, the Xpra web client allows users to unfocus modals. When a modal is triggered, the main window is frozen though, so if the modal is unfocused users are left with a frozen main window. By injecting some javascript, we can force modal windows to always be focused. This should reduce the amount of users that accidentally trigger a modal and then think their connection froze.
> fix: Fix an issue where modals could be unfocused causing soft-locks

- remote/rc.xml
This will only become visible after #336 is merged, since otherwise all windows are always in fullscreen mode.
> feat: Openbox theme improvements

- capella/setup/setup_workspace.py
Enable Capella's built-in UI freeze monitoring with default settings. I've been unable to trigger a situation where UI freezes are actually logged, so this needs more testing before being merged.
Closes #318
> feat: Automatically enable Capella UI freeze monitoring

- capella/autostart
Capella's diagram view doesn't add extra padding around the content. With overlay scrolling enabled, this frequently leads to the scrollbars popping up unintentionally, and the user being unable to properly interact with items on the bottom or right edge of the view.
Disabling the overlay scrolling feature makes the scrollbars always appear and reserve the space they need, thereby eliminating the issue.
> Disable overlay scrolling in Capella

- remote/Dockerfile
The previous fix unfortunately was not properly applied because OPEN_TIMEOUT was being read before being overwritten. By setting it before it's being read, the previous issues are fully fixed.
Closes #350
> fix: Fix the previous OPEN_TIMEOUT fix not being properly applied

- capella/Dockerfile
Previously, it was only installed when the debian base image had recommended installs on. In cases where it wasn't installed, disabling the BEL sound did not work.
Closes #294
> fix: Explicitly install x11-server-utils

- jupyter-notebook/Dockerfile
`less` is the default pager used for git commands. Without it, some git commands become almost unusable in the Jupyter terminal. One common example is `git log`, which will dump out the entire commit history onto the terminal, with the new and interesting commits being pushed way off screen (and sometimes out of the scroll buffer entirely).
> jupyter: Install less

- jupyter-notebook/Dockerfile
capellambse-context-diagrams no longer needs node to work, so we can remove it.
Closes #374
> feat: Remove node from jupyter image

- jupyter-notebook/docker-entrypoint.sh
In case uv fails to install from requirements.txt, reset it to the default and create a backup of the original one.
Closes #380
> fix: Handle requirements.txt being invalid in Jupyter

- capella/Dockerfile
- cli/cdi/capella/args.py
- cli/cdi/capella/build.py
- cli/cdi/capella/run.py
- cli/cdi/syncer/run.py
In https://github.com/DSD-DBS/capella-dockerimages/pull/392, `INSTALL_OLD_GTK_VERSION` has been changed to a default value of false. Since we want to focus on newer Capella versions going forward, we want to reduce the maintanance burden and therefore remove the option to install old GTK versions.
This will only affect users with Capella 5.X.X and 6.X.X with description editor issues.
> feat!: Remove support for old GTK versions

- cli/cdi/jupyter/build.py
- cli/cdi/jupyter/run.py
- cli/cdi/syncer/args.py
- cli/cdi/syncer/run.py
- cli/pyproject.toml
- t4c/t4c_cli/backup.py
- t4c/t4c_cli/util/capella.py
- t4c/t4c_cli/util/config.py
- t4c/t4c_cli/util/datetime.py
- t4c/t4c_cli/util/git.py
- t4c/t4c_cli/util/t4c.py
Until now, TeamForCapella commits were grouped and one Git commit was created per backup.
This commit introduces a new option to create one Git commit per TeamForCapella commit. This is more resource-intensive, but better for projects with high traceability needs.
TODO:
Resolves #309
> feat: Map TeamForCapella commits 1:1 to Git commits

- t4c/t4c_cli/backup.py
The T4C commit information is already contained in Git commits. There is no need to have it as file in the repository.
> fix(t4c2git): Don't copy commit history as file into Git repository

- cli/cdi/helpers.py
- remote/metrics.py
If the connection method isn't xpra, the xpra metrics are not relevant.
> perf: Don't register XpraCollector when using other connection method

- cli/cdi/capella/build.py
- cli/cdi/eclipse/build.py
- cli/cdi/papyrus/build.py
This is required for the CCM Makefile to push the `t4c/client/base` image.
> build: Also push intermediate images in CLI

- t4c/t4c_cli/backup.py
- t4c/t4c_cli/util/git.py
Since pre-commit hooks weren't executed anymore, Git LFS didn't work anymore. Reenable Git LFS by installing it in a separate environment.
> fix(backup): Reinstall Git LFS

- remote/supervisord.xpra.conf
This makes the Capella splashscreen visible on smaller devices as well.
> fix: Properly set initial screen resolution
